services:
  sigepa:
    image: nivspa/sigepa:latest
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1,.localhost}
      DB_NAME: ${DB_NAME:-sigepa} 
      DB_USER: ${DB_USER:-sigepa}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-3306}
    volumes:
      - media_data:/app/media
      - static_data:/app/staticfiles
      - logs_data:/app/logs
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M


volumes:
  media_data:
  static_data:
  logs_data:
