# Generated by Django 5.2.6 on 2025-09-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cbo',
            fields=[
                ('codigo', models.IntegerField(db_column='CODIGO', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, db_column='TITULO', max_length=255, null=True)),
            ],
            options={
                'db_table': 'cbo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cid',
            fields=[
                ('sk_causa', models.AutoField(primary_key=True, serialize=False)),
                ('nk_causa', models.CharField(blank=True, max_length=255, null=True)),
                ('num_cap', models.IntegerField(blank=True, null=True)),
                ('num_cap_rom', models.CharField(blank=True, max_length=255, null=True)),
                ('abrv_cap', models.CharField(blank=True, max_length=255, null=True)),
                ('abrv_cap_rom', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_subcategoria', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_cap', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_abrv_cap', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_grupo', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_abrv_grupo', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_abrv_categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_subcategoria', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_abrv_subcategoria', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id_escolaridade', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=70, unique=True)),
                ('ordem', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'escolaridade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estabelecimentos',
            fields=[
                ('co_unidade', models.BigIntegerField(db_column='CO_UNIDADE', primary_key=True, serialize=False)),
                ('no_fantasia', models.CharField(blank=True, db_column='NO_FANTASIA', max_length=255, null=True)),
                ('co_municipio_gestor', models.CharField(blank=True, db_column='CO_MUNICIPIO_GESTOR', max_length=25, null=True)),
                ('nu_cnpj', models.CharField(blank=True, db_column='NU_CNPJ', max_length=25, null=True)),
                ('co_cnes', models.CharField(blank=True, db_column='CO_CNES', max_length=25, null=True)),
                ('dt_atualizacao', models.CharField(blank=True, db_column='DT_ATUALIZACAO', max_length=25, null=True)),
                ('tp_unidade', models.IntegerField(blank=True, db_column='TP_UNIDADE', null=True)),
                ('nu_cpf', models.CharField(blank=True, db_column='NU_CPF', max_length=25, null=True)),
            ],
            options={
                'db_table': 'estabelecimentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idestado', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvolucaoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('outros_procedimentos', models.CharField(blank=True, max_length=100, null=True)),
                ('outros_complicacoes', models.CharField(max_length=100)),
                ('espaco_acolher', models.CharField(blank=True, max_length=1, null=True)),
                ('data_entrada_espaco_acolher', models.DateField(blank=True, null=True)),
                ('data_saida_espaco_acolher', models.DateField(blank=True, null=True)),
                ('data_obito', models.DateField(blank=True, null=True)),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('evolucao', models.TextField(blank=True, null=True)),
                ('nome_investigador', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'evolucao_tratamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvolucaoTratamentoHasTipoComplicacao',
            fields=[
                ('pk', models.CompositePrimaryKey('evolucao_tratamento_id', 'tipo_complicacao_idtipo_complicacao', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'evolucao_tratamento_has_tipo_complicacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvolucaoTratamentoHasTipoProcedimento',
            fields=[
                ('pk', models.CompositePrimaryKey('evolucao_tratamento_id', 'tipo_procedimento_idtipo_procedimento', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'evolucao_tratamento_has_tipo_procedimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id_municipio', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_uf', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('regiao_geografica_intermediaria', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_regiao_geografica_intermediaria', models.CharField(blank=True, max_length=255, null=True)),
                ('regiao_geografica_imediata', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_regiao_geografica_imediata', models.CharField(blank=True, max_length=255, null=True)),
                ('mesorregiao_geografica', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_mesorregiao', models.CharField(blank=True, max_length=255, null=True)),
                ('microrregiao_geografica', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_microrregiao', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'municipios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_notificacao', models.DateField()),
                ('data_acidente', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateField(blank=True, null=True)),
                ('nome_paciente', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('idade', models.CharField(blank=True, max_length=3, null=True)),
                ('cartao_sus', models.CharField(blank=True, max_length=15, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('distrito', models.CharField(blank=True, max_length=60, null=True)),
                ('bairro', models.CharField(blank=True, max_length=60, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=5, null=True)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('geo_campo1', models.CharField(blank=True, max_length=45, null=True)),
                ('geo_campo2', models.CharField(blank=True, max_length=45, null=True)),
                ('ponto_referencia', models.CharField(blank=True, max_length=45, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('num_registro', models.CharField(max_length=45)),
                ('tipo_motor', models.CharField(blank=True, max_length=45, null=True)),
                ('data_investigacao', models.DateField(blank=True, null=True)),
                ('nome_dono', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone_dono', models.CharField(blank=True, max_length=15, null=True)),
                ('nome_condutor', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone_condutor', models.CharField(blank=True, max_length=15, null=True)),
                ('data_atendimento', models.DateField(blank=True, null=True)),
                ('causa_acidente_outros', models.CharField(blank=True, max_length=45, null=True)),
                ('info_atendimento', models.TextField(blank=True, null=True)),
                ('transferencia_hospitalar', models.CharField(blank=True, max_length=1, null=True)),
                ('data_transferencia', models.DateField(blank=True, null=True)),
                ('unidade_transferencia', models.CharField(blank=True, max_length=80, null=True)),
                ('data_cadastro_atendimento', models.DateField(blank=True, null=True)),
                ('nome_invertigador', models.CharField(max_length=150)),
                ('funcao_invertigador', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ocorrencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaHasTipoParteAtingida',
            fields=[
                ('pk', models.CompositePrimaryKey('ocorrencia_id', 'tipo_parte_atingida_idtipo_parte_atingida', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ocorrencia_has_tipo_parte_atingida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idpais', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PovoTradicional',
            fields=[
                ('id_povo_tradicional', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45, unique=True)),
                ('ordem', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'povo_tradicional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id_raca', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45, unique=True)),
                ('ordem', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'raca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('idsexo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'sexo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempoGestacao',
            fields=[
                ('id_gestante', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45, unique=True)),
                ('ordem', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'tempo_gestacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCausaAcidente',
            fields=[
                ('idtipo_causa_acidente', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'tipo_causa_acidente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoComplicacao',
            fields=[
                ('idtipo_complicacao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_complicacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEscalpelamento',
            fields=[
                ('idtipo_escalpelamento', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'tipo_escalpelamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEvolucaoCaso',
            fields=[
                ('idtipo_evolucao_caso', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_evolucao_caso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoNotificacao',
            fields=[
                ('idtipo_notificacao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_notificacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoParteAtingida',
            fields=[
                ('idtipo_parte_atingida', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'tipo_parte_atingida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProcedimento',
            fields=[
                ('idtipo_procedimento', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_procedimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoRegimeAtendimento',
            fields=[
                ('idtipo_regime_atendimento', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_regime_atendimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTransporte',
            fields=[
                ('idtipo_transporte', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipo_transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('idzona', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'zona',
                'managed': False,
            },
        ),
    ]
